name: mingym
description: "A minimalist gym tracking app built with Flutter and Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.4.3
  fl_chart: ^1.1.1
  uuid: ^4.5.3
  shared_preferences: ^2.3.2
  csv: ^6.0.0
  path_provider: ^2.1.4
  share_plus: ^10.1.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  permission_handler: ^11.3.0
  firebase_crashlytics: ^4.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
